backend:
  name: github
  repo: jasonsutter87/GrowHugoChunkyPoster
  branch: master # Branch to update (optional; defaults to master)


# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - label: "Homepage - Companies Websites We Built" # Used in the UI
    name: "indexPage " # Used in routes, e.g., /admin/collections/blog
    description: "index page"
    create: true # Allow users to create new documents in this collection
    files:
      - label: "CompaniesWebsitesWeBuilt"
        name: "CompaniesWebsitesWeBuilt"
        file: "data/home/companiessitsewebuilt.toml"
        fields:
          - label: "Companies"
            name: "companies"
            widget: "list"
            fields:
              - {label: Url, name: url, widget: string}
              - {label: Alt, name: alt, widget: string}
              - {label: Image, name: image, widget: image}
